version: "3"

services:
  db:
    image: 'mysql:5.7'
    restart: always
    environment:
      - "MYSQL_DATABASE=recipe"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3309:3306"
    volumes:
      - ./data:/var/lib/mysql
  
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: /scripts/entrypoint.sh
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    # command: >
    #   sh -c "python manage.py wait_for_db && 
    #          python manage.py migrate &&
    #          python manage.py runserver 0.0.0.0:8000"
    environment:
      - "DB_HOST=db"
      - "DB_NAME=recipe"
      - "DB_USER=root"
      - "DB_PASS=password"
    depends_on:
      - db
